import {
  UserAccount,
  TeacherEntity,
  CourseEntity,
  ExamEntity,
  ExamStatus,
  AudioVisualDeptEntity,
  OperationsDeptEntity,
  AdminEntity,
  SecurityAuditLog,
  AppNotification,
} from './types.ts';

export const INITIAL_USERS: UserAccount[] = [
  {
    id: 'T001',
    username: 'somchai.t',
    role: 'Teacher',
    name: 'ผศ.ดร.สมชาย ใจดี',
    email: 'somchai.j@sci.ac.th',
    tel: '081-234-5678',
    department: 'สาขาวิชาวิทยาการคอมพิวเตอร์ คณะวิทยาศาสตร์',
    status: 'active',
  },
  {
    id: 'T002',
    username: 'waree.p',
    role: 'Teacher',
    name: 'รศ.ดร.วารี สุขสวัสดิ์',
    email: 'waree.s@sci.ac.th',
    tel: '089-987-6543',
    department: 'สาขาวิชาคณิตศาสตร์และสถิติ คณะวิทยาศาสตร์',
    status: 'active',
  },
  {
    id: 'AVD01',
    username: 'av.staff1',
    role: 'AudioVisual',
    name: 'นายกิตติศักดิ์ ช่างพิมพ์ (หน่วยโสตฯ)',
    email: 'audiovisual@sci.ac.th',
    tel: '02-555-2000 ต่อ 1204',
    department: 'หน่วยเทคโนโลยีการศึกษา (ฝ่ายโสตฯ)',
    location: 'อาคารวิทยาการ ชั้น 2 ห้องปฏิบัติการผลิตสื่อและจัดพิมพ์',
    status: 'active',
  },
  {
    id: 'OD01',
    username: 'ops.officer',
    role: 'Operations',
    name: 'นางสาวธนภรณ์ อำนวยการ (ฝ่ายดำเนินการสอบ)',
    email: 'exam-ops@sci.ac.th',
    tel: '02-555-2000 ต่อ 1100',
    department: 'ฝ่ายดำเนินการสอบและทะเบียนกลาง',
    location: 'อาคารเรียนรวม ศูนย์อำนวยการสอบ ชั้น 1',
    status: 'active',
  },
  {
    id: 'ADM01',
    username: 'admin.sci',
    role: 'Admin',
    name: 'นายผู้ดูแลระบบ ศูนย์สารสนเทศ',
    email: 'admin-it@sci.ac.th',
    tel: '02-555-2000 ต่อ 1001',
    department: 'ศูนย์เทคโนโลยีสารสนเทศ คณะวิทยาศาสตร์',
    status: 'active',
  },
];

export const INITIAL_TEACHERS: TeacherEntity[] = [
  {
    T_ID: 'T001',
    T_Name: 'สมชาย',
    T_Lname: 'ใจดี',
    T_Email: 'somchai.j@sci.ac.th',
    T_Tel: '081-234-5678',
    Department: 'สาขาวิชาวิทยาการคอมพิวเตอร์',
  },
  {
    T_ID: 'T002',
    T_Name: 'วารี',
    T_Lname: 'สุขสวัสดิ์',
    T_Email: 'waree.s@sci.ac.th',
    T_Tel: '089-987-6543',
    Department: 'สาขาวิชาคณิตศาสตร์และสถิติ',
  },
  {
    T_ID: 'T003',
    T_Name: 'ประสิทธิ์',
    T_Lname: 'คงมั่น',
    T_Email: 'prasit.k@sci.ac.th',
    T_Tel: '086-333-4444',
    Department: 'สาขาวิชาฟิสิกส์ประยุกต์',
  },
];

export const INITIAL_COURSES: CourseEntity[] = [
  {
    Course_id: 'CS211',
    Course_Name: 'โครงสร้างข้อมูลและขั้นตอนวิธี (Data Structures & Algorithms)',
    Course_year: '2567',
    term: '1',
    sec: '01',
    credits: 3,
    student_count: 75,
    teacher_id: 'T001',
    teacher_name: 'ผศ.ดร.สมชาย ใจดี',
  },
  {
    Course_id: 'CS342',
    Course_Name: 'ระบบจัดการฐานข้อมูล (Database Management Systems)',
    Course_year: '2567',
    term: '1',
    sec: '01',
    credits: 3,
    student_count: 60,
    teacher_id: 'T001',
    teacher_name: 'ผศ.ดร.สมชาย ใจดี',
  },
  {
    Course_id: 'MA102',
    Course_Name: 'แคลคูลัส 2 สำหรับวิทยาศาสตร์ (Calculus II for Science)',
    Course_year: '2567',
    term: '1',
    sec: '02',
    credits: 3,
    student_count: 120,
    teacher_id: 'T002',
    teacher_name: 'รศ.ดร.วารี สุขสวัสดิ์',
  },
  {
    Course_id: 'SC101',
    Course_Name: 'วิทยาศาสตร์กายภาพและสิ่งแวดล้อม',
    Course_year: '2567',
    term: '1',
    sec: '01',
    credits: 3,
    student_count: 90,
    teacher_id: 'T003',
    teacher_name: 'ผศ.ประสิทธิ์ คงมั่น',
  },
];

export const INITIAL_EXAMS: ExamEntity[] = [
  {
    E_No: 'EX-2567-001',
    E_Date: '2026-10-14',
    E_Time: '09:00 - 12:00 น.',
    Subject_ID: 'CS211',
    Subject_Name: 'โครงสร้างข้อมูลและขั้นตอนวิธี',
    exam_type: 'กลางภาค',
    Course_year: '2567',
    term: '1',
    teacher_id: 'T001',
    teacher_name: 'ผศ.ดร.สมชาย ใจดี',
    teacher_tel: '081-234-5678',
    room: 'SC-401 (ห้องบรรยายใหญ่)',
    total_pages: 8,
    total_copies: 75,
    copies_reserve: 5,
    status: 'PRINTED',
    file_name: 'CS211_Midterm_Exam_Final_Confidential.pdf',
    file_size: '2.4 MB',
    upload_date: '2026-09-01 14:30',
    checked_by: 'นายกิตติศักดิ์ ช่างพิมพ์ (หน่วยโสตฯ)',
    verified_date: '2026-09-03 10:15',
    print_date: '2026-09-05 16:00',
    envelope_notes: 'ข้อสอบมี 8 หน้า 5 ข้อใหญ่ ให้นำเครื่องคิดเลขวิทยาศาสตร์เข้าได้ ห้ามนำเอกสารเข้า',
    allowed_materials: ['เครื่องคิดเลขวิทยาศาสตร์', 'ปากกาน้ำเงิน/ดำ', 'ดินสอ 2B'],
    proctors: ['อาจารย์สมเกียรติ พิทักษ์', 'อาจารย์นิภา ดำรงค์ศิลป์'],
  },
  {
    E_No: 'EX-2567-002',
    E_Date: '2026-10-15',
    E_Time: '13:30 - 16:30 น.',
    Subject_ID: 'CS342',
    Subject_Name: 'ระบบจัดการฐานข้อมูล',
    exam_type: 'กลางภาค',
    Course_year: '2567',
    term: '1',
    teacher_id: 'T001',
    teacher_name: 'ผศ.ดร.สมชาย ใจดี',
    teacher_tel: '081-234-5678',
    room: 'SC-LAB-3 (ห้องคอมพิวเตอร์)',
    total_pages: 6,
    total_copies: 60,
    copies_reserve: 3,
    status: 'PRINTING',
    file_name: 'CS342_Database_Midterm_v2.pdf',
    file_size: '1.8 MB',
    upload_date: '2026-09-04 09:12',
    checked_by: 'นายกิตติศักดิ์ ช่างพิมพ์ (หน่วยโสตฯ)',
    verified_date: '2026-09-06 11:00',
    envelope_notes: 'จัดพิมพ์แบบเย็บมุมบนซ้าย บรรจุซองกันแสงพร้อมประทับตราลับ',
    allowed_materials: ['กระดาษสรุป (Cheat Sheet) A4 เขียนด้วยลายมือ 1 แผ่น'],
    proctors: ['ผศ.ดร.สมชาย ใจดี', 'นายธนาธิป ผู้ช่วยสอน'],
  },
  {
    E_No: 'EX-2567-003',
    E_Date: '2026-10-16',
    E_Time: '09:00 - 12:00 น.',
    Subject_ID: 'MA102',
    Subject_Name: 'แคลคูลัส 2 สำหรับวิทยาศาสตร์',
    exam_type: 'กลางภาค',
    Course_year: '2567',
    term: '1',
    teacher_id: 'T002',
    teacher_name: 'รศ.ดร.วารี สุขสวัสดิ์',
    teacher_tel: '089-987-6543',
    room: 'SC-AUDITORIUM (หอประชุมวิทยาการ)',
    total_pages: 10,
    total_copies: 120,
    copies_reserve: 8,
    status: 'SUBMITTED',
    file_name: 'MA102_Calculus2_ExamPaper.pdf',
    file_size: '3.1 MB',
    upload_date: '2026-09-08 16:45',
    envelope_notes: 'ตรวจนับชุดข้อสอบให้ครบ 128 ชุด (รวมสำรอง) ห้ามนำเครื่องคิดเลขเข้าห้องสอบเด็ดขาด',
    allowed_materials: ['ปากกา', 'ดินสอ', 'ยางลบ'],
    proctors: ['รศ.ดร.วารี สุขสวัสดิ์', 'ดร.ชาญวิทย์ วงศ์ดี', 'น.ส.กานดา ผู้ประสานงาน'],
  },
  {
    E_No: 'EX-2567-004',
    E_Date: '2026-10-18',
    E_Time: '13:30 - 15:30 น.',
    Subject_ID: 'SC101',
    Subject_Name: 'วิทยาศาสตร์กายภาพและสิ่งแวดล้อม',
    exam_type: 'กลางภาค',
    Course_year: '2567',
    term: '1',
    teacher_id: 'T003',
    teacher_name: 'ผศ.ประสิทธิ์ คงมั่น',
    teacher_tel: '086-333-4444',
    room: 'SC-202',
    total_pages: 5,
    total_copies: 90,
    copies_reserve: 5,
    status: 'DELIVERED_OD',
    file_name: 'SC101_PhysicalSci_Midterm.pdf',
    file_size: '1.2 MB',
    upload_date: '2026-08-28 11:20',
    checked_by: 'นายกิตติศักดิ์ ช่างพิมพ์ (หน่วยโสตฯ)',
    verified_date: '2026-08-30 14:00',
    print_date: '2026-09-02 10:30',
    envelope_notes: 'จัดส่งซองข้อสอบปิดผนึกพร้อมลายเซ็นกำกับปากซองให้ฝ่ายดำเนินการสอบเรียบร้อยแล้ว',
    allowed_materials: ['ปากกาลูกลื่น'],
    proctors: ['ผศ.ประสิทธิ์ คงมั่น', 'อาจารย์สมใจ บุญชู'],
  },
];

export const INITIAL_AUDIT_LOGS: SecurityAuditLog[] = [
  {
    id: 'LOG-101',
    timestamp: '2026-09-08 16:45:10',
    userId: 'T002',
    userName: 'รศ.ดร.วารี สุขสวัสดิ์',
    role: 'Teacher',
    action: 'UPLOAD_EXAM',
    subjectId: 'MA102',
    subjectName: 'แคลคูลัส 2 สำหรับวิทยาศาสตร์',
    ipAddress: '192.168.10.45',
    details: 'อัปโหลดไฟล์ข้อสอบต้นฉบับ MA102_Calculus2_ExamPaper.pdf (ขนาด 3.1 MB) พร้อมเข้ารหัสความปลอดภัย',
  },
  {
    id: 'LOG-102',
    timestamp: '2026-09-06 11:00:22',
    userId: 'AVD01',
    userName: 'นายกิตติศักดิ์ ช่างพิมพ์ (หน่วยโสตฯ)',
    role: 'AudioVisual',
    action: 'UPDATE_STATUS',
    subjectId: 'CS342',
    subjectName: 'ระบบจัดการฐานข้อมูล',
    ipAddress: '192.168.20.12',
    details: 'ตรวจสอบข้อสอบผ่านเกณฑ์ และเปลี่ยนสถานะเป็น [กำลังดำเนินการจัดพิมพ์] (ยอดพิมพ์ 60 ชุด + สำรอง 3)',
  },
  {
    id: 'LOG-103',
    timestamp: '2026-09-05 16:00:15',
    userId: 'AVD01',
    userName: 'นายกิตติศักดิ์ ช่างพิมพ์ (หน่วยโสตฯ)',
    role: 'AudioVisual',
    action: 'PRINT_ENVELOPE',
    subjectId: 'CS211',
    subjectName: 'โครงสร้างข้อมูลและขั้นตอนวิธี',
    ipAddress: '192.168.20.12',
    details: 'สั่งพิมพ์ใบปะหน้าซองข้อสอบและพิมพ์ข้อสอบเสร็จสิ้น พร้อมประทับตราและจัดเก็บเข้าตู้นิรภัย',
  },
  {
    id: 'LOG-104',
    timestamp: '2026-09-02 11:00:00',
    userId: 'OD01',
    userName: 'นางสาวธนภรณ์ อำนวยการ (ฝ่ายดำเนินการสอบ)',
    role: 'Operations',
    action: 'UPDATE_STATUS',
    subjectId: 'SC101',
    subjectName: 'วิทยาศาสตร์กายภาพและสิ่งแวดล้อม',
    ipAddress: '192.168.30.5',
    details: 'รับมอบซองข้อสอบปิดผนึกจากหน่วยโสตฯ และลงทะเบียนเข้าห้องมั่นคงพร้อมจัดสอบ',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'N-01',
    title: 'ข้อสอบใหม่รอการตรวจสอบ',
    message: 'รศ.ดร.วารี ได้อัปโหลดข้อสอบรายวิชา MA102 แคลคูลัส 2 เข้าสู่ระบบแล้ว กรุณาตรวจสอบความถูกต้อง',
    timestamp: '10 นาทีที่แล้ว',
    targetRole: 'AudioVisual',
    type: 'info',
    isRead: false,
    relatedExamNo: 'EX-2567-003',
  },
  {
    id: 'N-02',
    title: 'ข้อสอบพิมพ์และบรรจุซองเสร็จแล้ว',
    message: 'ข้อสอบวิชา CS211 โครงสร้างข้อมูล ได้รับการจัดพิมพ์และบรรจุซองเรียบร้อยแล้ว รอส่งมอบฝ่ายดำเนินการ',
    timestamp: '2 ชั่วโมงที่แล้ว',
    targetRole: 'Teacher',
    type: 'success',
    isRead: false,
    relatedExamNo: 'EX-2567-001',
  },
  {
    id: 'N-03',
    title: 'ส่งมอบซองข้อสอบเรียบร้อย',
    message: 'ฝ่ายดำเนินการสอบได้รับมอบซองข้อสอบวิชา SC101 แล้ว เก็บรักษาในห้องมั่นคงเรียบร้อย',
    timestamp: '1 วันที่แล้ว',
    targetRole: 'Operations',
    type: 'info',
    isRead: true,
    relatedExamNo: 'EX-2567-004',
  },
];

export const STATUS_LABELS: Record<ExamStatus, { label: string; badgeClass: string; step: number }> = {
  DRAFT: {
    label: 'ยังไม่ได้ส่งข้อสอบ',
    badgeClass: 'bg-slate-100 text-slate-700 border-slate-300',
    step: 1,
  },
  SUBMITTED: {
    label: 'ส่งแล้ว (รอโสตฯ ตรวจสอบ)',
    badgeClass: 'bg-amber-50 text-amber-800 border-amber-300',
    step: 2,
  },
  REJECTED: {
    label: 'ขอให้อัปโหลดใหม่ (ส่งกลับแก้ไข)',
    badgeClass: 'bg-rose-50 text-rose-800 border-rose-300',
    step: 2,
  },
  VERIFIED: {
    label: 'ตรวจสอบผ่านแล้ว',
    badgeClass: 'bg-blue-50 text-blue-800 border-blue-300',
    step: 3,
  },
  PRINTING: {
    label: 'กำลังจัดพิมพ์',
    badgeClass: 'bg-indigo-50 text-indigo-800 border-indigo-300 animate-pulse',
    step: 4,
  },
  PRINTED: {
    label: 'พิมพ์และบรรจุซองแล้ว',
    badgeClass: 'bg-purple-50 text-purple-800 border-purple-300',
    step: 5,
  },
  DELIVERED_OD: {
    label: 'ส่งมอบฝ่ายดำเนินการสอบแล้ว',
    badgeClass: 'bg-teal-50 text-teal-800 border-teal-300',
    step: 6,
  },
  READY_FOR_EXAM: {
    label: 'พร้อมสอบ (ในห้องมั่นคง)',
    badgeClass: 'bg-emerald-50 text-emerald-800 border-emerald-300',
    step: 7,
  },
};
